CREATE DATABASE AWS_USERS_DB;

CREATE TABLE AWS_USERS_TABLE (
  USER_ID INTEGER,
  USER_NAME VARCHAR(255),
  ACCOUNT_STATUS VARCHAR(255)
);

INSERT INTO AWS_USERS_TABLE (USER_ID, USER_NAME, ACCOUNT_STATUS)
VALUES (99, 'John Smith', 'free');

INSERT INTO AWS_USERS_TABLE (USER_ID, USER_NAME, ACCOUNT_STATUS)
VALUES (77, 'Alex Fray', 'premium');

INSERT INTO AWS_USERS_TABLE (USER_ID, USER_NAME, ACCOUNT_STATUS)
VALUES (02, 'Joe Slack', 'admin');

SELECT * FROM AWS_USERS_TABLE;