myASG:
  Type: AWS::AutoScaling::AutoScalingGroup
  Properties:
    VPCZoneIdentifier:
      - subnet-069207cfe245734d0
    LaunchTemplate:
      LaunchTemplateId: !Ref launchConfigTemplate
      Version: !GetAtt launchConfigTemplate.LatestVersionNumber
    MaxSize: '4'
    MinSize: '2'
    DesiredCapacity: '2'

launchConfigTemplate:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    ImageId: ami-00ee4df451840fa9d
    InstanceType: t2.micro
    SecurityGroups:
      - !Ref SSHSecurityGroup
      - !Ref HTTPSecurityGroup
    IamInstanceProfile: !Ref EC2InstanceProfile
  UserData:
      Fn::Base64: |
#!/bin/bash
        sudo yum -y update
        sudo yum -y install java-1.8.0-openjdk

  SSHSecurityGroup:
    Description: This security group is configured for SSH access
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  HTTPSecurityGroup:
    Description: This security group is configured for HTTP access
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref S3Role

  S3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: '/'
